name: Compose 2

on:
    push:
        paths:
            - .github/workflows/build_compose.yml
            - compose.test2.yml
            - compose.test2.ci.yml

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - 
                name: Check Cache of Docker Registry
                id: cache
                uses: actions/cache/restore@v3
                with:
                    path: /tmp/docker-registry
                    key: docker-registry-${{ github.ref }}-${{ github.sha }}
                    lookup-only: true
            -   
                name: Cache Docker Build Cache
                if: steps.cache.outputs.cache-hit != 'true'
                uses: actions/cache@v3
                with:
                    path: /tmp/.buildx-cache
                    key: docker-build-cache-${{ github.ref }}-${{ github.sha }}
                    restore-keys: |
                        docker-build-cache-${{ github.ref }}
                        docker-build-cache-
            - 
                name: Get Cache of Docker Registry
                if: steps.cache.outputs.cache-hit != 'true'
                uses: actions/cache@v3
                with:
                    path: /tmp/docker-registry
                    key: docker-registry-${{ github.ref }}-${{ github.sha }}
                    restore-keys: |
                        docker-registry-${{ github.ref }}
                        docker-registry-
            - 
                uses: docker/setup-buildx-action@v2
                if: steps.cache.outputs.cache-hit != 'true'
                with:
                    driver-opts: network=host
            -
                name: Make directories
                if: steps.cache.outputs.cache-hit != 'true'
                run: |
                    mkdir -p /tmp/docker-registry /tmp/.buildx-cache /tmp/.buildx-cache-new
                    ls -al /tmp
            - 
                run: docker run -d -p 5000:5000 --restart=always --name registry -v /tmp/docker-registry:/var/lib/registry registry:2
                if: steps.cache.outputs.cache-hit != 'true'
            -
                run: npx wait-on tcp:5000
                if: steps.cache.outputs.cache-hit != 'true'
            -
                name: Call
                if: steps.cache.outputs.cache-hit != 'true'
                run: curl http://localhost:5000/v2/_catalog
            - 
                uses: actions/checkout@v3
                if: steps.cache.outputs.cache-hit != 'true'
            -
                name: Build images
                if: steps.cache.outputs.cache-hit != 'true'
                uses: docker/bake-action@v2
                with:
                    push: true
                    files: |
                        "compose.test2.yml"
                        "compose.test2.ci.yml"
                    set: |
                        "*.cache-from=type=local,src=/tmp/.buildx-cache"
                        "*.cache-to=type=local,dest=/tmp/.buildx-cache-new"
            - 
                name: Move build cache files
                if: steps.cache.outputs.cache-hit != 'true'
                run: |
                    rm -rf /tmp/.buildx-cache
                    mv /tmp/.buildx-cache-new /tmp/.buildx-cache

    test:
        runs-on: ubuntu-latest
        needs: [build]
        steps:
            - 
                uses: actions/checkout@v3
            - 
                name: Get Cache of Docker Registry
                id: get-registory-cache
                uses: actions/cache/restore@v3
                with:
                    path: /tmp/docker-registry
                    key: docker-registry-${{ github.ref }}-${{ github.sha }}
                    fail-on-cache-miss: true
            -
                name: Start registory server
                run: docker run -d -p 5000:5000 --restart=always --name registry -v /tmp/docker-registry:/var/lib/registry registry:2
            -
                name: Compose up
                run: docker compose -f compose.test2.yml -f compose.test2.ci.yml up
